#!/bin/sh 

# to use:
#  1) edit CP below to match your local setup
#  2) edit PATH or change the script for: ajc,scalac,java 

# setup class paths 
CP=/usr/local/scala-2.7.3.final/lib/scala-library.jar:/usr/local/aspectj1.6/lib/aspectjrt.jar
rm -rf bin1 bin2 
mkdir -p bin1 bin2

#echo commands
set -x

#compile
scalac -d bin1 -target:jvm-1.5 -cp $CP src/example/*.scala src/example/*.java || exit

#weave
ajc -1.5 -d bin2 -cp $CP -inpath bin1 src/example/*.aj || exit

# run
java -cp $CP:bin2 example.Main

